spring:
  application:
    name: Spring-AI
  ai:
    openai:
      base-url: https://sg.uiuiapi.com
      api-key: sk-v6HOGpyvHSDjR4Jmddo5S1qyiJvdiwGwwFYRQmvpjzWzvODa
      chat:
        completions-path: /v1/chat/completions
        options:
          model: qwen-flash
      embedding:
        options:
            model: text-embedding-3-small
            dimensions: 1024
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecnu_edu_1?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 20040102
logging:
  level:
    org.springframework.ai: debug
    com.Spring-AI: debug